### ISSUE TITLE
properties-maven-plugin don't include the license file

### ISSUE THREAD

**Issue by puntogil** [mojohaus/properties-maven-plugin#2]
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
thanks
regards

**Comment by khmarbaise** [comment]
Can you check if this fulfils the requirements?

**Comment by puntogil** [comment]
hi
for me is ok!
thanks!
