### ISSUE TITLE
Unwarranted "Circular property definition"

### ISSUE THREAD

**Issue by julienwilliams** [mojohaus/properties-maven-plugin#27]
Running in 1.0.0

Running the following Test Unit fails but should not. It should be possible to reference the same property twice in another property as this is not a circular reference.

```
@Test
public void unwarrantedCircularReferenceError() throws MojoFailureException
{
    Properties properties = new Properties();
    properties.setProperty( "port", "8080" );
    properties.setProperty( "myCustomProperty", "http://${port}:${port}/" );

    String value = resolver.getPropertyValue( "myCustomProperty", properties, new Properties() );

    assertEquals( "http://8080:8080/", value );
}
```

Thank you,

Julien Williams

**Comment by ayen-tibco** [comment]
Can someone push out a new release for this plugin to get this bug fix?Thanks.

**Comment by Zefiro** [comment]
I also just stumbled upon this issue. Does the proposed fix from 2016-03-22 (two days short of one year back) solve this issue? If so, I'd appreciate if it could be merged.

**Comment by bobtiernay-okta** [comment]
Would it be possible to release version 1.0.1 which contains the fix? Much appreciated!

FYI - found this via https://stackoverflow.com/questions/39710828/maven-circular-property-definition.

**Comment by bobtiernay-okta** [comment]
@olamy Would this be something you could assist with?
