### ISSUE TITLE
Read Environment variables from .yml file

### ISSUE THREAD

**Issue by durimkryeziu** [mojohaus/properties-maven-plugin#36]
Hi,

I'm working on Spring Boot application and I have my app configuration under **application.yml** file, when I try to access one of my properties into another maven plugin I get error.

This is configuration of your plugin @robertotru:
```
<plugin>
    <groupId>it.ozimov</groupId>
    <artifactId>yaml-properties-maven-plugin</artifactId>
    <version>1.1.1</version>
    <executions>
        <execution>
            <phase>initialize</phase>
            <goals>
                <goal>read-project-properties</goal>
            </goals>
            <configuration>
                <files>
                    <file>src/main/resources/application.yml</file>
                </files>
            </configuration>
        </execution>
    </executions>
</plugin>
```

When I try to access like this, It can't recognize it
`<username>${app.datasource.username}</username>`

application.yml:
```
app:
  datasource:
    username: ${USERNAME}
```
**USERNAME** is an environment variable

When I tried with static value it worked awesome, but with Environment variables it doesn't work

Thanks

**Comment by robertotru** [comment]
@durimkryeziu You opened an issue on the wrong project! 

Anyway, if you type `${USERNAME}` in a yaml file, the value for the placeholder is not set by magic. 
You should try with the proper goal, e.g. `write-project-properties`.

**Comment by durimkryeziu** [comment]
@robertotru Thanks for replay, but I can't open issues on this project:
https://github.com/ozimov/yaml-properties-maven-plugin

No, it's supposed that I don't have access on the Env. Vars. I just have to brought the .war file and someone else sets values for Env. Vars. Get it ?

**Comment by robertotru** [comment]
Are you sure you cannot open issues?

Anyway, I think that you misunderstood the purpose of the plugin. If you need to pass a global variable to a maven POM you do not need the plugin at all.

For your convenience, read [this](http://stackoverflow.com/questions/10463077/how-to-refer-environment-variable-in-pom-xml) Stackoverflow answer.

**Comment by durimkryeziu** [comment]
Yes, I'm sure, there is no way I can create an issue while you forked this project.

No, I didn't, I want to use this plugin to read some properties from application.yml file and there I reference some environment variables.
I want to deploy this **.war** file into Tomcat and there we have a file **setenv.sh** where we have environment variables. I can't access these env vars through ${env.VAR_NAME}.
As I can't access env vars from **setenv.sh** wanted to read from application.yml through this plugin as Spring can read env vars from setenv.sh as I described here:
```
app:
  datasource:
    username: ${USERNAME}
```

Thanks

**Comment by khmarbaise** [comment]
The given configuration 
```xml
 <groupId>it.ozimov</groupId>
    <artifactId>yaml-properties-maven-plugin</artifactId>
    <version>1.1.1</version>
```
does not belong to this plugin...this is mojohaus...groupId: org.codehaus.mojo artifactId: properties-maven-plugin ... So i will close this issue cause it does not belong here...If you have other details / informations etc. please don't hesitate to reopen this issue...
