### ISSUE TITLE
error on goal properties:write-project-properties when properties file exists and is read-only

### ISSUE THREAD

**Issue by cristyrye** [mojohaus/properties-maven-plugin#50]
Is there a flag to allow writing the properties file if there already is a properties file and it is read only?
I am getting the following error:
[INFO] --- properties-maven-plugin:1.0.0:write-project-properties (default) @ template_basic_application ---
[ERROR] Could not create FileOutputStream: null
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.900 s
[INFO] Finished at: 2019-04-22T17:10:38+03:00
[INFO] Final Memory: 9M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:properties-maven-plugin:1.0.0:write-project-properties (default) on project template_basic_application: d:\IMS\UTIPNextGen\code\next_frameworks\template_basic_application\src\main\resources\app.properties (Access is denied) -> [Help 1]

**Comment by slawekjaranowski** [comment]
There is not such flag. If you want override files in your workspace you should allow it and change mode of file.
