### ISSUE TITLE
temp files are not automatically deleted in windows

### ISSUE THREAD

**Issue by ImadBL** [mojohaus/properties-maven-plugin#79]
Hi,

I use properties-maven-plugin to do some evolutions and I found a problem in unit tests, temp files are not automatically deleted in windows. I corrected that maybe be merged soon

**Comment by ImadBL** [comment]
> 

can you tell me how can i send a merge request?
**Can't create a new pull request: Push failed: remote: Permission to mojohaus/properties-maven-plugin.git denied to ImadBL. unable to access 'https://github.com/mojohaus/properties-maven-plugin.git/': The requested URL returned error: 403**

**Comment by slachiewicz** [comment]
Please first fork our repo and then push branch to yours fork. Gh then should help with hint to open PR

**Comment by ImadBL** [comment]
thanks @slachiewicz

**Comment by ImadBL** [comment]
#80
