### ISSUE TITLE
active development?

### ISSUE THREAD

**Issue by jgangemi** [mojohaus/properties-maven-plugin#98]
is there any active development going on for this plugin? i'd be happy to help w/ getting pull requests merged, rebased, etc.

**Comment by Mikhail2048** [comment]
@jgangemi We have created the fork for this plugin and implemented several features requested in this issues already. You can help us if you want :) Much appreciated :)

Here is the project:https://github.com/Mikhail2048/properties-maven-plugin

**Comment by slawekjaranowski** [comment]
Hi 
Thanks everybody for your efforts.

I can help with merging proposed PR and finally release next version.
Please mention me at PR - I will have it on my list.

I next week I will work on versions-m-p, so ping me in a week or two.

**Comment by slawekjaranowski** [comment]
We have many open issue and PR ... in order to make some of cleanups I have created milestone for next-release

https://github.com/mojohaus/properties-maven-plugin/milestone/3

As I wrote please mention me at issues and PR to help which is the most important 😄

**Comment by slawekjaranowski** [comment]
answering the question - yes - the project is maintained
so I close this issue.
